
name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        goos: [ linux, darwin, windows  ]
        goarch: [ amd64, arm64 ]
        include:
          - goos: windows
            ext : ".exe"
        exclude:
          - goos: windows
            goarch: arm64
    runs-on: ubuntu-latest
    steps:
      - name: Update example
        run: go test -v -run TestExample ./ellyn_ast/

      - name: Release Example
        run: npm install vite -g --save && cd viewer && npm install --dependencies && npm run build && cd ../example && go build -v -o example_app${{ matrix.ext }} .
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0

      # 把二进制文件打包成压缩文件
      - name: Prepare Packaging
        run: cd example &&  tar zcvf ellyn-example-${{ matrix.goos }}-${{ matrix.goarch }}.tgz example_app${{ matrix.ext }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ellyn-example-${{ matrix.goos }}-${{ matrix.goarch }}
          path: example/ellyn-example-${{ matrix.goos }}-${{ matrix.goarch }}.tgz
      # 发布release版本
      - name: Release version
        uses: ncipollo/release-action@v1
        if: github.event_name == 'release'
        with:
          allowUpdates: true
          artifacts: ellyn-example-${{ matrix.goos }}-${{ matrix.goarch }}
          token: ${{ secrets.GITHUB_TOKEN }}